### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by svitalis123** [chuaindia/ROR_Group_Project#14]
# RoR group project: set up your Kanban board

> Our GitHub project https://github.com/chuaindia/ROR_Group_Project

> Our group consists of 2 partners

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @svitalis123 and @chuaindia, 

To highlight 👍🏽 
✔️ Board has all the required columns
✔️ Cards are assigned to students

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
